In [8]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

# Imports
import numpy as np
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

Extracting MNIST_data\train-images-idx3-ubyte.gz
Extracting MNIST_data\train-labels-idx1-ubyte.gz
Extracting MNIST_data\t10k-images-idx3-ubyte.gz
Extracting MNIST_data\t10k-labels-idx1-ubyte.gz


In [3]:
sess = tf.InteractiveSession()

In [4]:
x = tf.placeholder(tf.float32, shape=[None, 784])
y_ = tf.placeholder(tf.float32, shape=[None, 10])
W = tf.Variable(tf.zeros([784,10]),name = 'W')
b = tf.Variable(tf.zeros([10]),name = 'b')

In [5]:
sess.run(tf.global_variables_initializer())
y = tf.matmul(x,W) + b
probs =  tf.nn.softmax_cross_entropy_with_logits(labels=y_, logits=y)
reg = tf.contrib.layers.apply_regularization(tf.contrib.layers.l1_regularizer(1.0),[W,b])
cross_entropy = tf.reduce_mean(probs)+0.1*reg
train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

In [9]:
for _ in range(10):
  batch = mnist.train.next_batch(1)#   train_step.run(feed_dict={x: batch[0], y_: batch[1]})
  _, loss_val,prob_vals = sess.run([train_step, cross_entropy,probs],
                             feed_dict={x: batch[0], y_: batch[1]})
  print(batch[1])

[[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]]
[[ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]]
[[ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]]
[[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]]


In [136]:
a = np.array([1,2,3,4,5,6])
b = np.reshape(a, [a.size // 3, 3]).transpose()
print(b)

[[1 4]
 [2 5]
 [3 6]]


In [123]:
out = [row for row in b]
print(out)

[array([1, 4]), array([2, 5]), array([3, 6])]


In [138]:
np.repeat(b, 3, 1)

array([[1, 1, 1, 4, 4, 4],
       [2, 2, 2, 5, 5, 5],
       [3, 3, 3, 6, 6, 6]])

In [169]:
mat = np.array([[1,2,3],[6,5,4]])


print(np.repeat(mat, 3, 1))
print(mat[:,-1])
b=mat[:,-1]
print(b.dtype)
xx = np.concatenate((mat,np.reshape(b,[2,1])),1)
print(xx)

[[1 1 1 2 2 2 3 3 3]
 [6 6 6 5 5 5 4 4 4]]
[3 4]
int32
[[1 2 3 3]
 [6 5 4 4]]


In [24]:
import pandas as pd
df = pd.DataFrame(np.zeros([5,5]))

# import os
# cwd = os.path.abspath(os.getcwd())
# path = os.path.join(cwd, "/save_model/model_iter")
# print(dir)
df.to_csv('model_iter.csv')